# Generated by Django 4.1.5 on 2023-02-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("restaurant", "0002_booking_delete_table_and_more")]

    operations = [migrations.RenameModel(old_name="Menu", new_name="MenuItem")]
